version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - test/e2e
