config_version = "0"

test_patterns = ["**/*_test.go"]
exclude_patterns = ["**/*_test.go"]

[[triage]]
match.rules = ["radarlint-go:S100"]
set.ignored = true

[[triage]]
match.rules = ["qlty:return-statements"]
match.file_patterns = ["main.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:boolean-logic"]
match.file_patterns = ["**/tui/peers.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:return-statements"]
match.file_patterns = ["**/tui/model.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:return-statements"]
match.file_patterns = ["**/cilium/conntrack.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:function-complexity"]
match.file_patterns = ["**/tui/keyhandlers.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:file-complexity"]
match.file_patterns = ["**/tui/keyhandlers.go", "**/tui/views.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:return-statements"]
match.file_patterns = ["**/cilium/json.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:file-complexity"]
match.file_patterns = ["**/cilium/filter.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:function-complexity"]
match.file_patterns = ["**/capture/differ.go"]
set.ignored = true

[[triage]]
match.rules = ["qlty:file-complexity"]
match.file_patterns = ["**/cilium/json.go"]
set.ignored = true
